"""initial migration

Revision ID: d26e0246e564
Revises: 
Create Date: 2026-05-24 10:48:11.748050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26e0246e564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('companies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('tenth_marks', sa.Float(), nullable=True),
    sa.Column('twelfth_marks', sa.Float(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('resume_filename', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)

    op.create_table('placement_drives',
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('eligibility', sa.String(length=200), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drive_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.drive_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('student_id', 'drive_id', name='unique_application')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('placement_drives')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))

    op.drop_table('students')
    op.drop_table('companies')
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
